version: "2"

services:
  web:
    build: ./web/
    env_file:
      - ./web/.env
    ports:
      - "8000:8000"
    links:
    - mysql
    volumes:
      - ./web:/code
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: django
      MYSQL_PASSWORD: django
      MYSQL_DATABASE: django
      MYSQL_USER: django
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: django
      PMA_PASSWORD: django
    ports:
      - 8083:80

volumes:
  mysql: